name: Deploy to FTP Server

on:
  push:
    branches:
      - main   # or the branch you use for deployment

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftp.bestratedhospitals.org
          username: fem@bestratedhospitals.org
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: /   # adjust to your FTP directory
          local-dir: ./               # your repo root